services:
  app:
    #image: gg-marketing-tool-backend-app
    build: .
    ports:
      - "19006:19006"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    entrypoint: ["npm", "run"]
    command: ["web"]
