name: Deploy to Olympus Server

on: 
  push:
    branches:
      -  dev
jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: Development

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

    - name: Copy files to DigitalOcean Droplet
      run: |
        rsync -avz --partial --delete -e "ssh -o StrictHostKeyChecking=no -o ConnectTimeout=500 -o ServerAliveInterval=60 -o ServerAliveCountMax=120" ./ kratos@${{ secrets.DROPLET_IP }}:~/native-card-mobile
       
    #rsync -avz --partial --delete -e "ssh -o StrictHostKeyChecking=no -o ConnectTimeout=500 -o ServerAliveInterval=60 -o ServerAliveCountMax=120" ./ kratos@${{ secrets.DROPLET_IP }}:~/native-card-mobile
     
    - name: SSH into DigitalOcean Droplet and deploy docker
      run: |
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=500 -o ServerAliveInterval=60 -o ServerAliveCountMax=120 kratos@${{ secrets.DROPLET_IP }} << 'EOF'
          npm config set fetch-retry-maxtimeout 120000
          cd ~/native-card-mobile
          docker compose down
          docker compose up --build -d
        EOF
