name: Deploy to Olympus Server

on: 
  push:
    branches:
      -  dev
jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: Development

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

    - name: Copy files to DigitalOcean Droplet
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ kratos@${{ secrets.DROPLET_IP }}:~/gg-marketing-tool-backend
    
    - name: Run npm build on DigitalOcean Droplet
      run: |
        ssh -o StrictHostKeyChecking=no kratos@${{ secrets.DROPLET_IP }} << 'EOF'
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm use 17.9.1
          cd ~/native-card-mobile
          npm install
          npm run build
        EOF

    - name: SSH into DigitalOcean Droplet and deploy docker
      run: |
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=500 kratos@${{ secrets.DROPLET_IP }} << 'EOF'
          cd ~/native-card-mobile
          docker compose down
          docker compose up --build -d
        EOF
